### ISSUE TITLE
BeautifulSoup(スクレイピング)からarXiv API利用へ変更

### ISSUE THREAD

**Issue by wakamezake** [fkubota/Carrier-Owl#19]
arXivにはPublicなarXivAPIが存在するので、そちらを使うほうが正しいアクセスの方法かと思います。

- https://arxiv.org/help/api/index
- https://github.com/lukasschwab/arxiv.py
- https://note.nkmk.me/python-arxiv-api-download-rss/

**Comment by fkubota** [comment]
@wakamezake   
ありがとうございます。
web周り全くの初心者で苦労してました。
変更します！

**Comment by wakamezake** [comment]
こちらでPR出そうかと思ってissue建てました

**Comment by fkubota** [comment]
@wakamezake   
BeautifulSoupで出力される論文数とことなりますね。  
wakamezakeさんの方法: 16本
fkubotaの方法: 3本

でした。何か心当たりはありますでしょうか？

**Comment by wakamezake** [comment]
arXivからの取得をsubmitした日付ソート後の上から1000件分を取得してます。この部分が差分になってますね、修正します。

**Comment by fkubota** [comment]
なるほど。
必然的に重複が生まれてしまいますね。  
こちらでも調査してみます。  
ありがとうございます。

**Comment by fkubota** [comment]
@wakamezake   
↓のfor文内で

https://github.com/fkubota/Carrier-Owl/blob/f4f76f2b2f22ca89954811e30473a1728ec4c419/src/carrier_owl.py#L43-L47

`day = article["published_parsed"].tm_mday`   
のように日付をチェックするif文いれればできそうですね。

queryでなげる時に指定できればいいんですが、、、

**Comment by wakamezake** [comment]
質問なのですがREADMEには前日のarxivと記載されていますが、検索対象の論文っていつまでを想定していますか？
(回答想定、最大1週間前から昨日までなど)

**Comment by fkubota** [comment]
@wakamezake 
ありがとうございます！
具体例で示しますと。

12/31に通知を行う場合、
12/30にpublishされた論文がSearch範囲になります。

**Comment by wakamezake** [comment]
元の処理をたどると最近投稿された日付のリストを下のページから取得して
![1](https://user-images.githubusercontent.com/7046610/103407002-27d43000-4ba0-11eb-9127-7a33a9bbfa6c.PNG)

今日がリストの0番目であればリストの2番目の日付の論文リンクを参照する
それ以外であれば1番目の日付の論文リンクを参照するという処理をしています。
上の画像の場合、今日が29日であれば12/23-12/24までに投稿された論文リストから検索をかける。

この処理の場合、日付のリスト内に前日(昨日)が入っているかをチェックされていないので期待されている動作ではないのかなと思いました。

**Comment by fkubota** [comment]
ちょっとすぐにはわからないのですが、年末ということで、26日以降に論文が出ていないので、リストに現れていないという可能性って考えられますか？

少なくとも、意図としては通知の前日になります。

**Comment by wakamezake** [comment]
arxiv apiの検索対象を昨日投稿された論文のみに修正したPR出しました

**Comment by fkubota** [comment]
ありがとうございます！
確認します！

**Comment by wakamezake** [comment]
論文が見つからなかった場合でも通知飛ぶようになっていますが修正したほうがいいですか？
この部分

https://github.com/wakamezake/Carrier-Owl/blob/b4f71a7191677d5cb97a43a6f1e273d87a80e44c/src/carrier_owl.py#L63-L66

**Comment by fkubota** [comment]
いえ、このままで問題ないです。

`問題なく動作しているが見つからなかった`  

ということがわかるので、このほうがいいかと。  
ありがとうございます。

**Comment by fkubota** [comment]
@wakamezake   
ありがとうございました。
マージ完了しましたので、クローズにしたいと思います。
