### ISSUE TITLE
複数領域指定対応

### ISSUE THREAD

**Issue by fkubota** [fkubota/Carrier-Owl#29]

**Comment by fkubota** [comment]
↓のcategoryを見れば良さそう。

https://arxiv.org/help/prep

**Comment by fkubota** [comment]
例えば、↓から、physics.space-phを選ぶなら、  
'cat: physics.space-ph' というふうにすれば良い。

 https://arxiv.org/archive/physics

**Comment by fkubota** [comment]
query例

- `cat:physics.space-ph OR cat:cs.ai`
- `cat:physics.* OR cat:cs.ai`

**Comment by wakamezake** [comment]
カテゴリの定義についてはこちらにも記載あり #24

**Comment by fkubota** [comment]
> カテゴリの定義についてはこちらにも記載あり #24
@wakamezake   
ありがとうございます。  
こちら、承知しております。  
細かい仕様が決まるまで取り急ぎの範囲でカテゴリ定義表を用意しようと考えています。
