### ISSUE TITLE
ChromedriverがChromeのversionに合わなくてGithub Actionがエラーで止まります

### ISSUE THREAD

**Issue by yamasakih** [fkubota/Carrier-Owl#59]
Carrier-Owlをクローンして利用させてもらっているものです。素敵なシステム作成ありがとうございます。

急にGithub Actionがエラーでワークしなくなったので確認したところ以下の画像のエラーが出ていました。
(私の環境だけでしたらすいません)

解決案として
* chromedriver追従してアップデートする
* (可能であれば)Github Actionで利用可能なGoogleのバージョンを固定する
 
の2つが考えられます。前者だと毎回アップデートのたびに追従するのが負担かなという懸念があります。  
私の方でもchromedriverをアップデートしてPRしようとしましたがインストール時にコケてしまうのでまず報告だけさせてもらいました。

chromedriver-binary v87 -> v89
https://pypi.org/project/chromedriver-binary/89.0.4389.23.0/

![image](https://user-images.githubusercontent.com/10294378/110956730-4586f800-838e-11eb-8984-26a36874d2dd.png)

**Comment by fkubota** [comment]
@yamasakih   
大変遅くなりました！  
ありがとうございます！  
たすかります！  
こちら、対応させていただきます！

**Comment by fkubota** [comment]
↓のPRでかいけつ

https://github.com/fkubota/Carrier-Owl/pull/61

**Comment by yamasakih** [comment]
@fkubota 対応ありがとうございました！試してみます！
