### ISSUE TITLE
アブストラクトの改行の有無について

### ISSUE THREAD

**Issue by dshintani404** [fkubota/Carrier-Owl#63]
出力されるアブストラクトに改行を入れていると思いますが、何か意図があるのでしょうか(slackだと見づらいなど)。
私は改行を取り除いてlineに通知していますが、他の方の意見も聞きたいと思いissueを立てました。

**Comment by fkubota** [comment]
@dshintani404   
ありがとうございます！  
これ、直したいなぁと思ってたんですがほったらかしにしちゃってました...  
もともと、個人で使っている時にトリプルクオーテーションで文を囲っていたんですよ。
その場合、文が長くても改行されないので無理やり改行入れてました。  
その名残です。今じゃトリプルクオーテーションを外しているので改行いらない気がしますね。  
この際直しちゃいますかねぇ。  

治すとするとLineでもslackでも両方取り除く方向になるとおもうのですがそれで問題ないでしょうか？

**Comment by dshintani404** [comment]
なるほど、そういう経緯でしたか。
Lineだと取り除くで問題ないですが、slackの方で同じ挙動かは確認したほうがよいかもしれません。

**Comment by fkubota** [comment]
返信おそくなってしまいました m(_ _)m  
ありがとうございます！  
取り掛かろうと思います！

**Comment by fkubota** [comment]
@dshintani404   
大変遅くなってしまいました...  
ご助言頂いた点を考慮して不要な改行を削除致しました。  
ありがとうございましたm(_ _)m
